### ISSUE TITLE
readme 里面的示意图是用什么软件画的？

### ISSUE THREAD

**Issue by Quintin-Z** [KitSprout/YellowBeanSprout#1]

**Comment by hom-wang** [comment]
Microsoft Visio
實際的文件可以在 Related Documents 裡下載

**Comment by Quintin-Z** [comment]
好的，不过用visio画起来还是挺麻烦的啊。对了，问问你们台湾那F446现在这个片子多少钱啊？

**Comment by hom-wang** [comment]
應該不算太麻煩，就是拉幾個方塊改改顏色，Power Point 也可以做到相同的效果，
STM32F446RE 我是在 Muser 上購買的，一片大概 360 台幣

**Comment by Quintin-Z** [comment]
好贵，大陆才45人民币上下。

**Comment by hom-wang** [comment]
我在淘寶上沒有看到 45 的 STM32F446RE，是直接跟當地的經銷商買的嗎？

mouser 大概 500 pcs 就低於 45 人名幣了，對樣品的需求確實比較貴，不過大型經銷商大概都這樣，
只是自己的學習研究用，需求不多，價差還是在可接受範圍內：）
